create table pessoas (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id));
alter table if exists pessoas add constraint UK_ouqc5requard3nhnb6u3wvksm unique (email);

create table pessoas (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id));
alter table if exists pessoas add constraint UK_ouqc5requard3nhnb6u3wvksm unique (email);
create table pessoas (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id));
alter table if exists pessoas add constraint UK_ouqc5requard3nhnb6u3wvksm unique (email);
create table pessoas (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id));
alter table if exists pessoas add constraint UK_ouqc5requard3nhnb6u3wvksm unique (email);
create table pessoas (id int8 generated by default as identity, email varchar(255) not null, name varchar(255) not null, primary key (id));
alter table if exists pessoas add constraint UK_ouqc5requard3nhnb6u3wvksm unique (email);
