
#spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=create.sql
#spring.jpa.properties.hibernate.hbm2ddl.delimiter=;
#spring.datasource.url=jdbc:postgresql://localhost:5432/test_integracao
#spring.datasource.username=postgres
#spring.datasource.password=vicente0301

#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.jpa.hibernate.ddl-auto=none
#spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/test_integracao
    username: postgres
    password: vicente0301
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER