name: Continuous Integration

on:
  push:
    branches:   
      - main 
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub account
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt' #temurin
        cache: maven
    - name: Build Application jar Maven
      working-directory: .
      run: mvn clean package # nunca usa o -DskipTest para pular os testes e colocar em producao

    - name: Docker Compose Build
      working-directory: .
      run: docker compose build

    - name: Push Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/atomated-test2:latest ${{ secrets.DOCKERHUB_USERNAME }}/atomated-test2:${{ github.run_id }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/atomated-test2:${{ github.run_id }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/atomated-test2:latest
